name: KiCad PCB Check

on:
  pull_request:
    paths:
      - '**/*.kicad_pcb'
    types: [opened, synchronize, reopened, assigned]

jobs:
  check-pcb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install KiCad tools (if needed)
      - name: Install KiCad
        id: kicad-inst
        run: |
          sudo add-apt-repository -y ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install --install-recommends -y kicad
      
      # Install Python & Deps
      - name: Install UV, Python, Dependencies
        id: python-deps
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv python install 3.12

      - name: Run Python Checks
        id: run-tests
        env:
          GH_TOKEN: ${{ secrets.PROPERTY_COLLEI_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPO: ${{ github.repository }}
        run: |
          cd ci 
          uv sync 
          uv run python main.py

      - name: Compress output folder
        id: output_compression
        run: tar -czvf output.tar.gz output/

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output.tar.gz
